### ISSUE TITLE
Can this renew itself when data changed?

### ISSUE THREAD

**Issue by minhncud** [speige/AspNetCore.ResponseCaching.Extensions#2]
I come here from "https://www.devtrends.co.uk/blog/custom-response-caching-in-asp.net-core-with-cache-invalidation". As i understand, this works like OutputCache. 
Did you think about create another custom ResponseCaching which can work with DistributedCache like DonutOutputCache? 
It's not easy for me to explain, so you can read this:
Example:
* I keep cache on both server and Redis
1) First request:
- Server gets data from database.
- Server creates a cache on server (names "server-cache") and keep a copy on Redis (names "redis-key") 
- Server sends data (with view) to client.
2) Second request: ("server-cache" does not expired)
- If data isn't changed: Server uses "server-cache" to send data to client
- If data in "redis-key" is changed, the "server-cache" is automatic renewed (remove, re-create with reset duration). 

![redis-core-cache](https://user-images.githubusercontent.com/36953180/44702588-63d1c480-aabe-11e8-8839-af1533702f84.png)

I'm trying to customize from Filter on MVC but my knowledge is not enough deep.

**Comment by speige** [comment]
You're correct that this works like OutputCache. I have not coded anything to make it work with DistributedCache or Redis. Feel free to fork my code & try to get it working yourself :)

If your knowledge isn't deep enough to code this yourself, you might want to try asking for help on StackOverflow. Unfortunately, I don't have any time available to train you. Sorry :(
